### ISSUE TITLE
Does it plays on frontend (browser) or backend (node)?

### ISSUE THREAD

**Issue by jersobh** [BigTeri/jscast#3]
I'm also creating a live stream radio, and I'm looking up for a solution to play the audio files on nodejs :(

**Comment by ardean** [comment]
There are both options available, backend and frontend.
You can use the [Speaker plugin type](https://github.com/ardean/jsCast#speaker) to pipe your audio directly to the speakers (backend). Or simply open the "Manage" webinterface (frontend).

CLI params to configure plugins:
**-t Speaker** or **--plugin-types Speaker**

And [here](https://github.com/ardean/jsCast#item-types) are the built in types.
Use the "File" Item type to play audio files from your filesystem.
